In [1]:
import numpy as np
import pandas as pd

In [2]:
customers = pd.read_csv('Multi Table end to end Project/customers.csv')
customers

   customer_id         name    segment region
0           C1   Customer_1  Corporate   East
1           C2   Customer_2   Consumer   East
2           C3   Customer_3  Corporate   West
3           C4   Customer_4  Corporate  South
4           C5   Customer_5  Corporate  North
5           C6   Customer_6   Consumer   West
6           C7   Customer_7   Consumer  North
7           C8   Customer_8  Corporate   West
8           C9   Customer_9   Consumer  North
9          C10  Customer_10   Consumer  North
10         C11  Customer_11   Consumer   East
11         C12  Customer_12   Consumer  South
12         C13  Customer_13   Consumer  South
13         C14  Customer_14   Consumer   West
14         C15  Customer_15   Consumer   West
15         C16  Customer_16  Corporate  South
16         C17  Customer_17   Consumer   West
17         C18  Customer_18   Consumer   West
18         C19  Customer_19   Consumer   West
19         C20  Customer_20  Corporate  South

In [3]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  20 non-null     str
 1   name         20 non-null     str
 2   segment      20 non-null     str
 3   region       20 non-null     str
dtypes: str(4)
memory usage: 772.0 bytes

In [7]:
customers.describe()

       customer_id        name   segment region
count           20          20        20     20
unique          20          20         2      4
top             C1  Customer_1  Consumer   West
freq             1           1        13      8

In [8]:
customers.isnull().sum()

customer_id    0
name           0
segment        0
region         0
dtype: int64

In [9]:
customers.duplicated().sum()

np.int64(0)

In [10]:
customers.to_csv('Multi Table end to end Project/cleaned_customers.csv')

In [11]:
order_details = pd.read_csv('Multi Table end to end Project/order_details.csv')

In [12]:
order_details

   order_id product_id  quantity   sales  profit
0       O40         P9         1  999.59  146.49
1       O23        P10         2  389.57  113.98
2       O12        P12         4  679.53  209.67
3       O20         P7         2  539.87  153.47
4        O8        P12         4  426.80  -47.03
..      ...        ...       ...     ...     ...
95      O10         P1         2  311.54  -15.30
96      O34         P9         1  101.63   -4.79
97      O19         P7         2  584.72  146.31
98      O31        P13         1  724.97  -63.69
99      O39         P8         3  891.70  -65.39

[100 rows x 5 columns]

In [13]:
order_details.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    100 non-null    str
 1   product_id  100 non-null    str
 2   quantity    100 non-null    int64
 3   sales       100 non-null    float64
 4   profit      100 non-null    float64
dtypes: float64(2), int64(1), str(2)
memory usage: 4.0 KB

In [14]:
order_details.describe()

         quantity       sales      profit
count  100.000000  100.000000  100.000000
mean     2.500000  561.638000   99.569500
std      1.159066  265.282176  122.100021
min      1.000000  101.630000  -98.380000
25%      1.000000  318.395000   -8.592500
50%      2.000000  591.890000  114.250000
75%      4.000000  787.647500  209.677500
max      4.000000  999.590000  294.670000

In [15]:
order_details.isnull().sum()

order_id      0
product_id    0
quantity      0
sales         0
profit        0
dtype: int64

In [16]:
order_details.duplicated().sum()

np.int64(0)

In [17]:
order_details.to_csv('Multi Table end to end Project/cleaned_order_details.csv')

In [18]:
orders = pd.read_csv('Multi Table end to end Project/orders.csv')
orders

   order_id customer_id  order_date   ship_date
0        O1         C20  2023-01-01  2023-01-03
1        O2         C18  2023-01-02  2023-01-04
2        O3         C16  2023-01-03  2023-01-05
3        O4          C8  2023-01-04  2023-01-06
4        O5          C7  2023-01-05  2023-01-07
5        O6         C16  2023-01-06  2023-01-08
6        O7         C11  2023-01-07  2023-01-09
7        O8          C2  2023-01-08  2023-01-10
8        O9         C18  2023-01-09  2023-01-11
9       O10         C14  2023-01-10  2023-01-12
10      O11         C12  2023-01-11  2023-01-13
11      O12         C14  2023-01-12  2023-01-14
12      O13          C7  2023-01-13  2023-01-15
13      O14         C17  2023-01-14  2023-01-16
14      O15         C15  2023-01-15  2023-01-17
15      O16         C16  2023-01-16  2023-01-18
16      O17         C18  2023-01-17  2023-01-19
17      O18          C9  2023-01-18  2023-01-20
18      O19         C18  2023-01-19  2023-01-21
19      O20         C16  2023-01-20  2023-01-22
20      O21         C20  2023-01-21  2023-01-23
21      O22         C14  2023-01-22  2023-01-24
22      O23         C12  2023-01-23  2023-01-25
23      O24         C10  2023-01-24  2023-01-26
24      O25         C15  2023-01-25  2023-01-27
25      O26         C17  2023-01-26  2023-01-28
26      O27         C15  2023-01-27  2023-01-29
27      O28         C18  2023-01-28  2023-01-30
28      O29          C3  2023-01-29  2023-01-31
29      O30         C17  2023-01-30  2023-02-01
30      O31          C7  2023-01-31  2023-02-02
31      O32         C20  2023-02-01  2023-02-03
32      O33         C19  2023-02-02  2023-02-04
33      O34          C6  2023-02-03  2023-02-05
34      O35         C14  2023-02-04  2023-02-06
35      O36         C12  2023-02-05  2023-02-07
36      O37         C14  2023-02-06  2023-02-08
37      O38          C3  2023-02-07  2023-02-09
38      O39         C13  2023-02-08  2023-02-10
39      O40          C2  2023-02-09  2023-02-11
40      O41          C1  2023-02-10  2023-02-12
41      O42          C2  2023-02-11  2023-02-13
42      O43         C16  2023-02-12  2023-02-14
43      O44          C1  2023-02-13  2023-02-15
44      O45         C14  2023-02-14  2023-02-16
45      O46          C5  2023-02-15  2023-02-17
46      O47          C3  2023-02-16  2023-02-18
47      O48          C6  2023-02-17  2023-02-19
48      O49          C3  2023-02-18  2023-02-20
49      O50          C7  2023-02-19  2023-02-21

In [19]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     str
 1   customer_id  50 non-null     str
 2   order_date   50 non-null     str
 3   ship_date    50 non-null     str
dtypes: str(4)
memory usage: 1.7 KB

In [20]:
orders['order_date']=pd.to_datetime(orders['order_date'],format='mixed',errors='coerce')
orders['order_date'].dtype

dtype('<M8[us]')

In [21]:
orders['ship_date']=pd.to_datetime(orders['ship_date'],format='mixed',errors='coerce')
orders['ship_date'].dtype

dtype('<M8[us]')

In [22]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     str
 1   customer_id  50 non-null     str
 2   order_date   50 non-null     datetime64[us]
 3   ship_date    50 non-null     datetime64[us]
dtypes: datetime64[us](2), str(2)
memory usage: 1.7 KB

In [23]:
orders.isnull().sum()

order_id       0
customer_id    0
order_date     0
ship_date      0
dtype: int64

In [24]:
orders.duplicated().sum()

np.int64(0)

In [25]:
orders.to_csv('Multi Table end to end Project/cleaned_orders.csv')

In [26]:
products = pd.read_csv('Multi Table end to end Project/products.csv')
products

   product_id         category sub_category product_name
0          P1  Office Supplies      Binders    Product_1
1          P2       Technology       Chairs    Product_2
2          P3       Technology       Chairs    Product_3
3          P4  Office Supplies      Storage    Product_4
4          P5        Furniture       Chairs    Product_5
5          P6  Office Supplies       Chairs    Product_6
6          P7  Office Supplies      Binders    Product_7
7          P8  Office Supplies      Storage    Product_8
8          P9       Technology      Binders    Product_9
9         P10  Office Supplies      Binders   Product_10
10        P11  Office Supplies      Storage   Product_11
11        P12        Furniture       Chairs   Product_12
12        P13        Furniture      Storage   Product_13
13        P14  Office Supplies      Binders   Product_14
14        P15       Technology      Binders   Product_15

In [27]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    15 non-null     str
 1   category      15 non-null     str
 2   sub_category  15 non-null     str
 3   product_name  15 non-null     str
dtypes: str(4)
memory usage: 612.0 bytes

In [28]:
products.describe()

       product_id         category sub_category product_name
count          15               15           15           15
unique         15                3            3           15
top            P1  Office Supplies      Binders    Product_1
freq            1                8            6            1

In [29]:
products.isnull().sum()

product_id      0
category        0
sub_category    0
product_name    0
dtype: int64

In [30]:
products.duplicated().sum()

np.int64(0)

In [31]:
products.to_csv('Multi Table end to end Project/cleaned_products.csv')

## Import to SQL ##

In [33]:
#customers
#order_details
#orders
#products

from sqlalchemy import create_engine
# engine = create_engine('posgresql://postgres:root@localhost:5432/MyDatabase')
# customers.to_sql('cleaned_customers',engine,if_exists='replace',index=False)
# order_details.to_sql('cleaned_order_details',engine,if_exists='replace',index=False)
# orders.to_sql('cleaned_orders',engine,if_exists='replace',index=False)
# products.to_sql('cleaned_products',engine,if_exists='replace',index=False)

In [35]:
engine = create_engine('postgresql://postgres:root@localhost:5432/MyDatabase')

In [36]:
customers.to_sql('cleaned_customers',engine,if_exists='replace',index=False)

20

In [37]:
order_details.to_sql('cleaned_order_details',engine,if_exists='replace',index=False)

100

In [38]:
orders.to_sql('cleaned_orders',engine,if_exists='replace',index=False)

50

In [39]:
products.to_sql('cleaned_products',engine,if_exists='replace',index=False)

15